project_name: m2c

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    binary: m2c

archive:
  replacements:
    386: i386
    amd64: x86_64
  wrap_in_directory: false
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^scratch:"
